name: typewriter
description: Visual quest configuration
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection:
  stack_trace:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  graphview: ^1.2.0
  flutter_hooks: 
  hooks_riverpod: ^2.3.8
  auto_size_text: ^3.0.0
  # google_fonts: ^4.0.4
  rive: ^0.12.3
  fuzzy: ^0.5.1
  auto_route: ^7.8.4
  collapsible: ^1.0.0
  riverpod_annotation: ^2.1.2
  ktx: ^1.1.6
  # Keep this as the older one since we use SocketIO v2 on the server.
  socket_io_client: 1.0.2
  clipboard: ^0.1.3
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.9
  color: ^3.0.0
  duration: ^3.0.13
  flutter_animate: ^4.3.0
  text_scroll: ^0.2.0
  url_launcher: ^6.1.12
  http:
  audioplayers: ^5.2.1
  collection_ext: ^1.0.0
  tinycolor2: ^3.0.1
  uuid: ^4.2.1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  icons_launcher: ^2.1.3
  auto_route_generator: ^7.2.0
  riverpod_generator: ^2.3.8
  custom_lint:
  riverpod_lint: ^2.3.6
  integration_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/Typewriter.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/materials/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic
