name: Build and Publish Release Jars

on:
  workflow_dispatch:

jobs:
  build-publish-release:
    runs-on: ubuntu-latest
    concurrency:
      group: build-publish-release
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build Engine
        uses: ./.github/actions/build-engine
#  ----------------------------------------------------------------------------------------------------
      - name: Build Extensions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildRelease --scan
          build-root-directory: ./extensions
      - name: Upload Jars as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Typewriter-Releases
          path: |
            engine/engine-paper/build/libs/Typewriter.jar
            extensions/**/build/libs/*.jar
          retention-days: 1
      - name: Reset Extensions Gradle Builds Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean --scan
          build-root-directory: ./extensions
#  ----------------------------------------------------------------------------------------------------
      - name: Publish Engine to Beta Maven Repository
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToTypewriterReleasesRepository -PTypewriterReleasesUsername=${{ secrets.MAVEN_USERNAME }} -PTypewriterReleasesPassword=${{ secrets.MAVEN_PASSWORD }} --scan
          build-root-directory: ./engine
      - name: Publish All Extensions to Beta Maven Repository
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToTypewriterReleasesRepository -PTypewriterReleasesUsername=${{ secrets.MAVEN_USERNAME }} -PTypewriterReleasesPassword=${{ secrets.MAVEN_PASSWORD }} --scan
          build-root-directory: ./extensions
#  ----------------------------------------------------------------------------------------------------
