on:
  push:
    branches:
      - main
      - develop
    paths:
      - "adapters/BasicAdapter/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "adapters/BasicAdapter/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/BasicAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/BasicAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: BasicAdapter.jar
          path: adapters/BasicAdapter/build/libs/BasicAdapter.jar
