on:
  push:
    branches:
      - main
      - dev
    paths:
      - "adapters/WorldGuardAdapter/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "adapters/WorldGuardAdapter/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/WorldGuardAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/WorldGuardAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: WorldGuardAdapter.jar
          path: adapters/WorldGuardAdapter/build/libs/WorldGuardAdapter.jar
