name: Deploy Discord Bot
on:
  push:
    branches:
      - develop
    paths:
      - "discord_bot/**"

jobs:
  deploy:
    name: Deploy Discord Bot
    runs-on: ubuntu-latest
    concurrency: deploy-discord-bot
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Discord Bot
        working-directory: discord_bot
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

