name: Test Documentation deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test Documentation deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          working-directory: ./documentation

      - name: Install dependencies
        run: npm ci
        working-directory: ./documentation
      - name: Test build website
        run: npm build
        working-directory: ./documentation
